# Generated by Django 3.0.7 on 2020-07-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_islikedcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='images/ava.png', upload_to='images/'),
        ),
    ]
